overrides:
  - files: "*.md"
    options:
      printWidth: 120
      tabWidth: 2
      useTabs: false
      semi: false
      singleQuote: false
      trailingComma: "none"
      bracketSpacing: true
      proseWrap: "always"
